name: for_fajr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flame: ^1.29.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0-dev.7
  functions_client: ^2.4.1
  intl: ^0.20.2
  mock_supabase_http_client: ^0.0.3+2
  native_geofence: ^1.0.9
  permission_handler: ^11.4.0
  realtime_client: ^2.4.2
  storage_client: ^2.3.1
  supabase: ^2.6.3
  supabase_auth_ui: ^0.5.5
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
